CREATE TABLE IF NOT EXISTS wallet (
  id UUID PRIMARY KEY,

  user_id UUID NOT NULL,

  name TEXT,

  network TEXT NOT NULL, 

  private_key BYTEA NOT NULL UNIQUE,
  public_key BYTEA NOT NULL UNIQUE,
  address TEXT UNIQUE,

  created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP, 
  updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
  deleted_at TIMESTAMPTZ,

  FOREIGN KEY (user_id) REFERENCES users(id),
)
