CREATE TABLE IF NOT EXISTS users (
  id UUID PRIMARY KEY,
  secret BYTEA NOT NULL UNIQUE,
  wallet,
  create_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMPTZ,
  update_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMPTZ,
  delete_at TIMESTAMPTZ
)
