CREATE TABLE IF NOT EXISTS users (
  id UUID PRIMARY KEY,

  secret BYTEA NOT NULL UNIQUE,

  created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
  deleted_at TIMESTAMPTZ
)
