CREATE TABLE IF NOT EXISTS wallet (
  id UUID PRIMARY KEY,
  private_key BYTEA NOT NULL,
  public_key BYTEA NOT NULL,
  create_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMPTZ, 
  update_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMPTZ,
  delete_at TIMESTAMPTZ
)
