package wallet

import "github.com/uptrace/bun"

// Wallet represents a row of the "wallet" table and serves as the
// model for the Bun ORM to generate the corresponding SQL queries.
//
// PrivateKey (and PrivateViewKey, for monero) are stored
// envelope-encrypted: an inner AES-256-GCM layer keyed by a
// password-derived key (see PasswordSalt, package
// cryptography/vault), then an outer AES-256-GCM layer keyed by the
// server's WalletEncryptionKey. PublicKey/PublicViewKey/Address are
// public information and are stored as-is.
type Wallet struct {
	bun.BaseModel `bun:"table:wallet,alias:w"`

	// Id is a UUID generated by Postgres (DEFAULT gen_random_uuid()).
	Id string `bun:",pk,nullzero"`
	// UserId references the owning user (users.id).
	UserId string `bun:",notnull"`
	// Name is an optional user-facing label for this wallet.
	Name string `bun:",nullzero"`
	// Network is "bitcoin" or "monero".
	Network string `bun:",notnull"`

	// PrivateKey is the envelope-encrypted private key: the secp256k1
	// private key for bitcoin, the spend private key for monero.
	PrivateKey []byte `bun:",notnull"`
	// PublicKey is the public key in clear: the compressed secp256k1
	// public key for bitcoin, the spend public key for monero.
	PublicKey []byte `bun:",notnull"`
	// Address is the bitcoin address in clear. Empty for monero,
	// since address derivation is not implemented yet on the
	// generator side.
	Address string `bun:",nullzero"`

	// PrivateViewKey is the envelope-encrypted monero view private
	// key. Unused (nil) for bitcoin.
	PrivateViewKey []byte `bun:"private_view_key"`
	// PublicViewKey is the monero view public key in clear. Unused
	// (nil) for bitcoin.
	PublicViewKey []byte `bun:"public_view_key"`

	// PasswordSalt seeds the password-derived key used for the inner
	// encryption layer (see package cryptography/vault.DeriveKey).
	PasswordSalt []byte `bun:",notnull"`
}
