package user

import (
	"context"
	"fmt"
	"log"
	"net/http"
	"time"

	"gojo/internal/app"
	"gojo/internal/middleware"
)

func Health(w http.ResponseWriter, r *http.Request) {
	_, err := fmt.Fprint(w, "All is good\n")
	if err != nil {
		log.Fatal(err)
	}
}

// CreateUser registers a new account: it hashes the password with bcrypt
// (via middleware.HashPassword) and stores username + hash. The plaintext
// password never touches the database or the logs. It returns the new
// user's id (a UUID generated by Postgres).
func CreateUser(db *app.App, username, password string) (string, error) {
	hash, err := middleware.HashPassword(password)
	if err != nil {
		return "", fmt.Errorf("cannot hash password: %w", err)
	}

	ctx := context.Background()

	user := &User{Username: username, Secret: hash}
	if _, err := db.Database.NewInsert().Model(user).Exec(ctx); err != nil {
		return "", err
	}

	return user.Id, nil
}

// DeleteUser soft-deletes an account by id: it sets deleted_at instead of
// removing the row, consistent with the deleted_at column and with
// middleware.Login, which already excludes rows where deleted_at is set.
func DeleteUser(db *app.App, id string) error {
	ctx := context.Background()

	_, err := db.Database.NewUpdate().
		Model((*User)(nil)).
		Set("deleted_at = ?", time.Now()).
		Where("id = ?", id).
		Where("deleted_at IS NULL").
		Exec(ctx)

	return err
}
