package user

import "github.com/uptrace/bun"

type User struct {
	bun.BaseModel `bun:"table:users,alias:u"`

	// Id is a UUID generated by Postgres (DEFAULT gen_random_uuid() in the
	// migration). "nullzero" tells bun to omit the column on insert when the
	// Go value is still "", so the database default is used instead.
	Id       string `bun:",pk,nullzero"`
	Username string `bun:",notnull,unique"`
	// Secret stores the bcrypt hash of the password, never the password itself.
	Secret []byte `bun:",notnull"`
}
