package user

import "github.com/uptrace/bun"

// User represents a row of the "users" table and serves as the model
// for the Bun ORM to generate the corresponding SQL queries.
type User struct {
	// bun.BaseModel associates this struct with the "users" table (SQL alias "u").
	bun.BaseModel `bun:"table:users,alias:u"`

	// Id is a UUID generated by Postgres (DEFAULT gen_random_uuid() in the
	// migration). "nullzero" tells bun to omit the column on insert
	// when the Go value is still "", letting the database apply its
	// default value.
	Id string `bun:",pk,nullzero"`
	// Username must be unique and non-null (constraints enforced at the database level).
	Username string `bun:",notnull,unique"`
	// Secret stores the bcrypt hash of the password, never the plaintext password.
	Secret []byte `bun:",notnull"`
}
